---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: "unarchive backend files"
  unarchive: 
    dest: /home/ubuntu/
    src: backend.tar.gz
    
- name: Start PM2
  shell: |
    cd ~/backend
    pm2 start npm --name backend -- start
    #pm2 start npm -i 1 --name backend -- start
 