---
- name: "unarchive backend files"
  unarchive: 
    dest: /home/ubuntu/
    src: backend.tar.gz
    
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: Start PM2
  shell: |
    cd ~/backend
    pm2 start npm --name backend -- start
    #pm2 start npm -i 1 --name backend -- start
 